-- MySQL Script generated by MySQL Workbench
-- Wed Mar 28 09:24:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tdd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tdd` ;

-- -----------------------------------------------------
-- Schema tdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tdd` DEFAULT CHARACTER SET utf8 ;
USE `tdd` ;

-- -----------------------------------------------------
-- Table `tdd`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tdd`.`customer` ;

CREATE TABLE IF NOT EXISTS `tdd`.`customer` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tdd`.`fruit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tdd`.`fruit` ;

CREATE TABLE IF NOT EXISTS `tdd`.`fruit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tdd`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tdd`.`order` ;

CREATE TABLE IF NOT EXISTS `tdd`.`order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customerId` BIGINT UNSIGNED NULL,
  `fruitId` BIGINT UNSIGNED NULL,
  `weight` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
